services:
  web:
    image: nginx:latest
    ports:
      - "${WEB_HOST:-127.0.0.1}:${WEB_PORT:-8080}:80"
    volumes:
      - ./website:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - frontend
      - backend
    depends_on:
      - n8n
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"  # Use environment variable
      POSTGRES_USER: "${DB_USER}"          # Use environment variable
      POSTGRES_DB: "${DB_NAME}"            # Use environment variable
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-databases.sh:/docker-entrypoint-initdb.d/01-init-databases.sh
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 5s
      retries: 3

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "${N8N_PORT:-5678}:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - NODE_ENV=production
      - N8N_ENCRYPTION_KEY="${N8N_ENCRYPTION_KEY}"  # Use environment variable
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_CORS_ENABLED=true
      - N8N_CORS_ALLOW_ORIGIN="${N8N_CORS_ORIGIN:-http://localhost:8080}"
      - EXECUTIONS_TIMEOUT=600  # 10 minutes
      - EXECUTIONS_TIMEOUT_MAX=3600  # 1 hour
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/custom-nodes:/home/node/.n8n/custom
      - ./n8n/local-files:/files
    networks:
      - backend
      - frontend
    healthcheck:
      test: ["CMD", "sh", "-c", "netstat -ln | grep 5678"]
      interval: 30s
      timeout: 10s
      retries: 3

  court-processor:
    build:
      context: ./court-processor
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      PYTHONPATH: /app
      COURTLISTENER_API_TOKEN: ${COURTLISTENER_API_TOKEN}
      PACER_USERNAME: ${PACER_USERNAME}
      PACER_PASSWORD: ${PACER_PASSWORD}
      RECAP_WEBHOOK_URL: http://recap-webhook:5000/webhook/recap-fetch
    volumes:
      - ./court-data/pdfs:/data/pdfs
      - ./court-data/logs:/data/logs
      - ./court-processor:/app
    depends_on:
      - db
      - recap-webhook
    networks:
      - backend
    restart: unless-stopped
  
  recap-webhook:
    build:
      context: ./court-processor/api
      dockerfile: Dockerfile
    environment:
      COURTLISTENER_API_TOKEN: ${COURTLISTENER_API_TOKEN}
      RECAP_DOWNLOAD_DIR: /data/recap_downloads
      RECAP_WEBHOOK_SECRET: ${RECAP_WEBHOOK_SECRET}
      FLASK_ENV: production
    ports:
      - "${RECAP_WEBHOOK_PORT:-5001}:5000"
    volumes:
      - ./court-data/recap_downloads:/data/recap_downloads
      - ./court-processor:/app/court-processor
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  lawyer-chat:
    build: 
      context: ./services/lawyer-chat
      dockerfile: Dockerfile
    container_name: lawyer-chat
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/lawyerchat
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=http://localhost:8080/chat
      - NEXT_PUBLIC_NEXTAUTH_URL=http://localhost:8080/chat
      - N8N_WEBHOOK_URL=http://n8n:5678/webhook/c188c31c-1c45-4118-9ece-5b6057ab5177
      - N8N_API_KEY=${N8N_API_KEY}
      - N8N_API_SECRET=${N8N_API_SECRET}
      # Email config
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      # Redis config
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - n8n
      - redis
    networks:
      - backend
      - frontend
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://0.0.0.0:3000/chat/api/csrf"]
      interval: 30s
      timeout: 10s
      retries: 3

  ai-portal:
    build:
      context: ./services/ai-portal
      dockerfile: Dockerfile
    container_name: ai-portal-app
    restart: unless-stopped
    networks:
      - frontend

  ai-portal-nginx:
    image: nginx:alpine
    container_name: ai-portal-nginx
    restart: unless-stopped
    ports:
      - "${AI_PORTAL_PORT:-8085}:80"
    volumes:
      - ./services/ai-portal/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ai-portal
    networks:
      - frontend

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  n8n_data:
  redis_data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge